language: bash

sudo: required
services:
  - docker

env:
    COMPOSE_VERSION: 1.20.1

global:
  - COMPOSE_FILE="-f docker-compose-web.yml"

before_install:
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - docker-compose ${COMPOSE_FILES} build --no-cache
