language: bash

sudo: required
services:
  - docker

env:
  global:
    # - COMPOSE_FILES="-f docker-compose-deb.yml"
    - COMPOSE_VERSION=1.20.1
    - COMPOSE_FILE="docker-compose-dev.yml"

before_install:
  - curl -L https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

script:
  - docker-compose build 
